const text = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus facilisis porttitor. Nullam sed eleifend purus. Sed vitae faucibus dui. Integer ut purus eu arcu lobortis malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vel luctus diam, eu hendrerit erat. Aliquam nisl dolor, congue vel tristique id, ullamcorper in odio. Suspendisse libero ligula, imperdiet at pellentesque vel, blandit sit amet felis. Cras eleifend mattis diam, quis consectetur nunc vulputate id. Proin euismod neque lorem, vitae scelerisque nisl porta vel. Phasellus sed dolor vel sem sodales accumsan non vitae mi. Phasellus erat sapien, dapibus vitae pellentesque ut, placerat sit amet nunc. Donec commodo sem risus, rutrum dapibus justo consectetur quis. In pretium, mi in posuere porttitor, odio leo ultricies felis, ac sodales enim velit id ligula. Maecenas efficitur vitae enim ac accumsan.",
  "Pellentesque elit mi, euismod non purus sit amet, vehicula fermentum mi. In faucibus convallis felis, ultricies tristique ex sodales sed. Praesent volutpat nulla augue, nec pharetra diam pretium sed. Curabitur dignissim dolor ut purus malesuada ullamcorper. Mauris commodo, tellus eget auctor tempor, risus elit tincidunt nibh, varius molestie ipsum odio sed purus. Vivamus mattis lacus mauris, scelerisque tincidunt turpis varius ac. Sed et magna mollis, fermentum nibh fermentum, iaculis mi. Suspendisse laoreet tempor orci. Praesent faucibus augue a velit tristique placerat. Cras in gravida ante, vel aliquam sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta risus sit amet volutpat suscipit. Fusce lectus risus, interdum at iaculis sit amet, consequat vitae ex. Mauris vitae pretium mauris. Proin ut nisi nec dolor iaculis varius.",
  "Phasellus quis ullamcorper tortor. Suspendisse potenti. Curabitur ultricies sapien vel arcu tincidunt vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas iaculis eleifend tempor. Nunc congue, urna et feugiat fermentum, urna dui commodo urna, id dapibus risus purus vel libero. Nulla condimentum elit at tempor euismod. Quisque sit amet orci at augue sollicitudin hendrerit. Phasellus aliquam ac ligula in molestie. Nulla quis diam magna. Donec condimentum et orci sed semper.",
  "Ut eu convallis orci. Aenean malesuada, risus quis interdum eleifend, lectus mi lobortis urna, vel sodales eros tortor ac arcu. Donec vulputate sapien quis lacus iaculis suscipit. Praesent euismod posuere tellus a mollis. Morbi sed maximus velit. Sed tempor non leo nec suscipit. Phasellus et ligula vel eros ornare lacinia quis sit amet dolor. Cras id sapien eu eros molestie lacinia in eget magna.",
  "Donec sagittis ex non viverra venenatis. Maecenas venenatis maximus cursus. Duis nibh magna, rutrum a metus ut, venenatis tristique neque. Duis eget nisi vel nisl mollis pharetra. Vivamus vel fermentum risus. Praesent pretium accumsan orci sed iaculis. Sed accumsan dictum sapien at condimentum. Mauris libero ante, imperdiet id maximus vitae, imperdiet in diam. Vestibulum mattis aliquet lacus vitae imperdiet.",
  "Phasellus euismod elit eu arcu pharetra, eget tristique augue mollis. Aliquam erat volutpat. Integer eget porta nulla. Sed pulvinar nulla id ligula vehicula, eget vestibulum arcu finibus. Nam malesuada nisi sed cursus pretium. Nam tempor tincidunt porta. Sed ut sapien metus. Vivamus diam ante, maximus ut urna sit amet, pulvinar vestibulum nunc. Maecenas vel libero ullamcorper, tincidunt purus ac, consequat nulla. Sed varius in orci sed interdum. Aenean tempus, est vitae sodales vehicula, mauris metus efficitur justo, sed maximus nulla nisi eget lectus.",
  "Vestibulum feugiat nisl odio, nec convallis massa facilisis ut. Aliquam at tellus tristique, dapibus justo ut, efficitur ligula. Phasellus non sem nec libero feugiat consectetur sit amet tincidunt nisl. Vivamus in tincidunt magna. Vestibulum lobortis consequat aliquet. Suspendisse placerat quis nisi id lobortis. Sed cursus porttitor ante in pulvinar. Suspendisse nec tortor fringilla, pulvinar magna in, viverra sem. Nullam convallis porttitor orci sit amet rhoncus. Vestibulum et metus quis leo ultrices vehicula. Pellentesque facilisis vitae quam vel dictum. Aenean eleifend in leo a rutrum.",
  "Sed vitae tincidunt nibh, non congue mi. Nunc ac posuere eros, sed sollicitudin risus. Pellentesque tempus fringilla blandit. Nunc dapibus odio in nisi tempus tincidunt. Phasellus non sagittis dui. Aliquam erat volutpat. In in bibendum velit. Etiam quis est massa. Aliquam vehicula scelerisque ullamcorper. Nam eget augue convallis, sollicitudin nibh sed, dignissim arcu. Donec vitae dictum odio, et interdum nunc. Nulla quis felis gravida, lacinia leo id, condimentum nisl. Maecenas luctus nibh et tellus mollis rhoncus. Nam tincidunt dui nisi, et feugiat diam consectetur eu. Nulla facilisi.",
  "Etiam sollicitudin, lectus sed sagittis interdum, sapien sem ultricies massa, vel interdum felis lacus id tellus. Maecenas augue quam, vestibulum id pharetra nec, imperdiet ac quam. Mauris facilisis orci vel molestie bibendum. Quisque sollicitudin arcu iaculis cursus gravida. Vestibulum id purus at quam vestibulum condimentum. Vestibulum auctor et urna et tristique. Duis quis facilisis neque. Donec gravida maximus iaculis. In mattis ante eget enim faucibus congue. Donec in sagittis tellus, et faucibus dolor.",
  "Nullam vitae congue lacus. Nam ac justo nec quam ullamcorper faucibus ut quis leo. Cras eu laoreet leo, et commodo nunc. Morbi maximus diam ex, tempus venenatis urna ornare at. Morbi euismod non risus ac accumsan. Ut vel eros sed neque accumsan fringilla eget a ligula. Suspendisse potenti. Morbi molestie quis est quis scelerisque.",
  "Ut in turpis tristique, vulputate nisl ut, pharetra lacus. Fusce euismod magna ac neque mattis, sit amet aliquet mauris hendrerit. Nulla facilisi. Donec a ipsum vitae dui malesuada faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc a neque sit amet ante egestas tincidunt non ut purus. Donec sed suscipit orci. Nulla arcu orci, consequat quis feugiat quis, vehicula sagittis ipsum. Proin nec placerat lacus. Curabitur nec massa vestibulum, volutpat enim ac, vehicula nunc. Proin ornare faucibus lorem, in interdum quam semper ut. Phasellus vestibulum turpis non faucibus ultricies. In faucibus libero nulla, sit amet mattis odio dignissim eu. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
  "Pellentesque placerat est turpis, et rutrum erat iaculis non. Curabitur laoreet leo sit amet nunc sollicitudin, ut tempor ex pulvinar. Mauris in accumsan quam. Duis sit amet sapien augue. Curabitur sit amet augue nec ipsum commodo mattis. Donec auctor, ligula vel efficitur accumsan, est neque porta est, et semper felis nisi nec enim. Ut eu ligula pharetra, ullamcorper tortor eu, sodales turpis. Morbi fringilla at quam eget vehicula. Nunc sed ante viverra, malesuada ligula non, sodales nunc. Suspendisse commodo metus nibh, non tempor orci facilisis quis. Integer semper vel justo eget molestie. Sed finibus odio ut arcu porta finibus.",
  "Nunc tellus mi, tincidunt in massa a, rutrum luctus justo. Nulla sed eleifend lorem. Ut lobortis risus et pretium porttitor. Etiam ac justo at dui tempus pellentesque sed vitae massa. Donec a accumsan justo, quis dignissim lacus. Mauris vitae venenatis dolor, dapibus suscipit justo. Aliquam erat volutpat. Phasellus nec urna diam. Fusce massa sem, interdum vitae ornare eget, vehicula id diam. Etiam sit amet neque ut massa fermentum pulvinar id ut ex. Vivamus iaculis diam id arcu malesuada, eget ullamcorper odio imperdiet. Mauris quis malesuada risus, in laoreet nisi. Donec dignissim vel tortor eu porta. Sed malesuada quam ut turpis dapibus, non ultricies nibh aliquet.",
  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis sapien libero, porta vitae diam pretium, luctus luctus lorem. Fusce blandit nulla ante, vel tempus nibh consectetur quis. Nunc viverra quis metus fermentum egestas. Fusce a elit sed dui tincidunt feugiat. In quis mollis sapien, quis malesuada arcu. Proin dapibus metus nunc, non gravida ligula scelerisque cursus. In maximus sollicitudin commodo. Etiam ac auctor ex. Proin fermentum tortor in tortor pretium molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas facilisis, sapien eu ultricies rhoncus, dui lacus dictum nibh, eu auctor dolor augue eu mi. Sed neque enim, bibendum sit amet justo aliquet, feugiat sollicitudin felis. Praesent ut vulputate felis. Ut a nulla leo. Sed at massa egestas, blandit tortor eu, mattis arcu.",
  "Vivamus in urna nec ligula elementum ultrices. Sed sollicitudin molestie libero et pellentesque. Praesent ut nunc ut nisi fermentum suscipit eu a ligula. Suspendisse pharetra pharetra leo, in pellentesque lectus tincidunt tempor. Sed urna tortor, porta pretium neque in, tempus suscipit erat. Quisque pellentesque pulvinar libero, eu semper mauris condimentum sed. Suspendisse potenti. Ut aliquam massa eget tellus luctus tincidunt. Nunc pulvinar eu erat ut dapibus.",
  "Sed quis tortor a nunc auctor elementum eget maximus nibh. Nullam maximus felis eu risus sollicitudin, vitae congue dui ullamcorper. Donec bibendum mi nunc, vel suscipit arcu dignissim et. Vivamus elementum enim sit amet libero sodales ullamcorper. Nulla et tellus ut diam convallis porta vehicula vitae nunc. Ut ut aliquet lorem. Quisque fermentum tincidunt ligula, sed efficitur nisi cursus ut. Curabitur tortor dolor, lacinia quis congue et, bibendum ut ligula. Ut venenatis tortor odio, eu iaculis velit facilisis a. Aliquam erat volutpat. Ut volutpat, tellus in consectetur sagittis, nisl orci venenatis lorem, in tincidunt sapien tellus at lacus. Nam tristique lorem id nisl finibus cursus. Aliquam congue a urna eu gravida.",
  "Etiam ac ornare tellus, eu consequat justo. Sed consectetur egestas leo, ut pharetra tellus sollicitudin luctus. Suspendisse ut nisi dolor. Donec vitae massa quam. Phasellus porttitor enim et tortor scelerisque rutrum. Donec orci massa, ullamcorper vitae maximus non, viverra nec leo. Proin sodales pretium eleifend. Pellentesque placerat leo nisl, a feugiat elit auctor eu. Praesent vitae consectetur urna. Vestibulum ut diam at mauris placerat bibendum a nec orci. Nam gravida, turpis vel auctor ornare, neque diam placerat enim, at luctus nibh leo sed purus. Fusce eleifend erat in ultricies lacinia. Sed mollis maximus mauris, vel ultricies tellus tempus sed.",
  "Nam suscipit, turpis ac lobortis tincidunt, augue urna mattis dui, ut consectetur odio dui bibendum erat. Nullam pretium eleifend ex, non imperdiet neque. Aenean eget lacinia elit. Vivamus aliquam, nunc at viverra sollicitudin, ipsum massa cursus ipsum, et venenatis tortor mi in nunc. Ut hendrerit non elit eu iaculis. Donec porttitor massa a auctor pharetra. Aenean at eros ante. Sed vel augue sit amet ligula suscipit auctor ac ut metus. Ut non suscipit turpis, ut condimentum mi. Phasellus pharetra ut libero sed pharetra. Praesent condimentum eleifend lectus, id vestibulum turpis dapibus fringilla. Phasellus a imperdiet velit, eget placerat erat.",
  "Sed nisi nunc, gravida vitae iaculis ac, posuere et lacus. Vestibulum placerat sem in enim iaculis, id interdum ipsum tincidunt. Vestibulum scelerisque dictum elementum. Aenean blandit condimentum lacus ac mollis. Quisque elementum id dui non laoreet. Proin venenatis, odio vestibulum venenatis efficitur, sapien lectus efficitur massa, non rhoncus lacus urna ut nunc. Praesent egestas ante luctus, pellentesque purus nec, vestibulum sem. Nunc condimentum orci a vehicula commodo. Etiam eu tellus venenatis, suscipit magna at, lobortis sem. Aenean risus magna, vestibulum vitae semper a, congue id ligula.",
  "Nunc augue diam, ornare mattis gravida nec, tempus elementum diam. Fusce eget lectus magna. Aliquam fermentum malesuada lectus, quis lacinia purus. Pellentesque vestibulum hendrerit justo in sollicitudin. Donec et lacus quam. Vestibulum quis blandit sapien. Vivamus placerat leo urna, id gravida odio ullamcorper eu. Cras lobortis diam sit amet orci ullamcorper, vitae accumsan diam commodo. In sed aliquam nibh. Suspendisse molestie augue non iaculis dictum. Cras non scelerisque metus, at hendrerit arcu. Nam nec dui elementum nunc dictum pharetra et ac turpis. Pellentesque quis neque eu mi lacinia commodo tempus ut nibh.",
  "Vestibulum non gravida ipsum. Sed mauris nulla, bibendum sed metus sit amet, porta elementum lectus. Suspendisse lobortis dictum nunc ut fringilla. Quisque sed consectetur ligula. Integer id odio nunc. Sed id fringilla erat. Ut arcu tellus, ornare et enim sed, vehicula sagittis purus. Nulla diam odio, bibendum at sem quis, efficitur tincidunt quam. Curabitur eu ante pulvinar, condimentum elit at, semper sem. Fusce tincidunt orci ac venenatis mattis. Nullam mattis tellus sed neque cursus, ac faucibus enim pellentesque.",
  "Ut bibendum justo interdum justo facilisis, eu dictum tellus ullamcorper. Suspendisse ut consequat justo, quis accumsan ante. Etiam et diam iaculis lectus viverra condimentum. Mauris sollicitudin orci est, in malesuada tellus tristique in. Etiam elementum velit eget finibus ullamcorper. Ut accumsan quis mi vitae convallis. Donec nec elit tortor. Sed a odio dignissim, ullamcorper mi vitae, tristique sem. Donec eu neque a lacus placerat venenatis. Curabitur non risus viverra, vulputate velit eget, luctus lectus. Cras volutpat sit amet turpis ut molestie. Nam aliquam tincidunt finibus. Nam vestibulum justo at pulvinar molestie. Phasellus sodales nisl vitae urna eleifend blandit. Aenean urna lectus, dictum ac accumsan at, ultricies et justo.",
  "Phasellus pharetra leo vel cursus molestie. Praesent sem diam, gravida a lectus sed, porttitor gravida justo. Sed accumsan felis dolor, nec convallis dolor bibendum eget. Sed mollis, nisl auctor sagittis porttitor, justo nulla hendrerit tellus, vel vestibulum ex sem ut neque. Nulla sodales ipsum justo, at eleifend nisl rhoncus sit amet. Morbi dignissim, tellus sed bibendum vestibulum, metus leo ullamcorper velit, at dignissim arcu nunc vitae ipsum. Pellentesque eleifend, sem a malesuada feugiat, risus arcu sagittis lectus, non venenatis libero massa a velit. Aliquam gravida dignissim orci, nec aliquet massa egestas a. Sed tristique nulla enim, id dignissim erat blandit non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque luctus orci ut lacinia dignissim. Cras a posuere eros. Pellentesque volutpat nulla bibendum aliquam tincidunt.",
  "Morbi et condimentum diam, eget rutrum nibh. Quisque convallis, lectus ac molestie feugiat, velit ex dictum dui, fermentum convallis nulla turpis quis sapien. Mauris viverra convallis augue nec tincidunt. Vestibulum a iaculis tortor. Sed eleifend lectus vel nunc gravida ornare. Donec sagittis varius nisi. Mauris a arcu ante. Cras finibus, mauris vel semper ornare, lorem nulla gravida neque, id fringilla diam odio id mi. Donec eu felis tortor. Ut vestibulum bibendum est, et commodo enim elementum porttitor. Pellentesque finibus nunc quam, sed accumsan justo mattis eget. Pellentesque blandit, massa non eleifend pretium, libero ex dictum ipsum, vitae fermentum neque mauris eu est. Sed sollicitudin eros vitae lorem condimentum, nec consectetur dui molestie.",
  "Nulla tempus augue eget massa consequat, at placerat turpis faucibus. Phasellus posuere gravida nibh nec elementum. Proin luctus risus sit amet faucibus egestas. Praesent laoreet pharetra ipsum et finibus. Pellentesque pulvinar lorem vitae dignissim bibendum. Donec faucibus sagittis velit eu molestie. Maecenas lectus lorem, vehicula non accumsan ut, fermentum id velit. Nulla vulputate, libero sit amet porttitor pulvinar, nibh nisl mattis ante, ut finibus urna velit non erat. Maecenas in placerat orci. Aenean faucibus odio nunc, nec vulputate enim rhoncus id. Nulla dictum luctus velit, et pharetra augue facilisis at. Quisque congue varius imperdiet. Praesent nec magna ex. Proin aliquam malesuada pulvinar. Sed commodo ex id faucibus congue.",
  "In at neque nisi. Nunc ut dui ut mauris iaculis semper. Nulla vulputate lobortis dui, id bibendum metus viverra vel. Fusce semper tortor congue fermentum scelerisque. In non dui eu lorem rhoncus scelerisque sed mollis lorem. In pulvinar vitae velit sit amet placerat. Mauris aliquam convallis sapien, sed consequat purus gravida ut. Praesent id quam placerat, luctus tortor quis, rhoncus augue. Ut vitae ligula urna. Aenean euismod sagittis odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras auctor purus non lorem pulvinar egestas. Praesent vitae metus metus. Ut mauris risus, cursus non mauris et, porta elementum ex. In hac habitasse platea dictumst.",
  "Cras euismod hendrerit arcu, sit amet aliquet magna iaculis vel. Proin ut erat ac nunc vehicula tincidunt. Mauris sit amet massa nec nisl efficitur rhoncus. Morbi a dui euismod, dictum augue a, placerat nibh. Phasellus sed pretium turpis. Nam ligula mauris, gravida at consequat a, rhoncus et urna. Donec sit amet est tristique, pellentesque tellus sit amet, faucibus nunc. Mauris pellentesque ac sapien quis ornare. Fusce hendrerit magna at risus efficitur eleifend. Proin non turpis fringilla, tincidunt lorem eu, laoreet libero. Integer faucibus vehicula magna, sagittis luctus sem placerat at. Nunc lacus ipsum, tempor eu euismod sit amet, tempus ut neque. Proin ut tortor at magna porttitor faucibus non sed neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla facilisi.",
  "Duis feugiat molestie efficitur. Aenean suscipit, nulla eget facilisis finibus, metus felis vulputate lacus, ac aliquet libero ligula vitae augue. Curabitur tincidunt risus nec lobortis tincidunt. Pellentesque nec neque a enim pretium pulvinar vel id urna. Praesent egestas, elit in tristique egestas, metus tellus hendrerit odio, nec ultrices massa erat in odio. Donec a odio a nibh accumsan sodales. Sed tortor leo, varius sit amet nisl quis, luctus iaculis augue. Cras blandit et enim ac tempus. Donec placerat dui sit amet accumsan tincidunt. Phasellus et risus augue. Aenean tincidunt nisi non arcu pretium viverra.",
  "Aenean turpis est, cursus sed ipsum non, rhoncus dapibus ex. Aenean convallis id quam vel rhoncus. Mauris interdum mauris diam, vitae hendrerit risus ultricies a. Sed non libero a justo rhoncus posuere. Aliquam consectetur libero ligula, sed volutpat purus interdum accumsan. Integer in lectus et sem tempus aliquam sit amet non mauris. Aenean ut lacus imperdiet, lobortis urna sed, placerat eros. Duis id est quam. In malesuada nisi eros, quis bibendum mi viverra at. Morbi lacinia, nisl sit amet ullamcorper lobortis, ipsum urna ullamcorper erat, vitae aliquet ex tortor a justo. Nullam suscipit felis libero, id tincidunt tellus consectetur eu. Praesent vulputate sollicitudin leo, ut convallis sem ultricies tristique. Integer vitae metus elit. Sed diam nunc, pellentesque et tincidunt nec, imperdiet et dolor. Donec at nibh vel massa euismod suscipit at dapibus ipsum. Quisque ac elit ex.",
  "Sed feugiat bibendum enim sit amet imperdiet. Duis sapien velit, suscipit vitae faucibus nec, viverra eget massa. Pellentesque pellentesque sem non metus laoreet, a viverra leo vulputate. Quisque sit amet luctus metus. Donec facilisis dignissim augue quis mattis. Vivamus sed ante lorem. Donec ac quam elementum, facilisis sem nec, accumsan massa. Proin at bibendum lacus. Nulla ut mollis sapien. Duis at posuere dolor. Donec ut efficitur eros. Nam dictum, risus ac egestas facilisis, augue nunc sollicitudin risus, sit amet dignissim nulla ex eget mi. Mauris sit amet sem quis neque luctus blandit nec nec lorem."
];

function* loremGen() {
  while (true)
    yield text[Math.floor(Math.random() * text.length)];
}

module.exports = {
  init: function () {
    const samples = (new Array(this.options.count || 1));
    this.samples = [...samples].map(() => this.rendText.next().value);
  },
  rendText: loremGen()
};
