# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain core dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    reviewers:
      - "@exadel-inc/esl-core-maintainers"
    assignees:
      - "ala-n"
      - "abarmina"
      - "NastaLeo"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      commit-lint:
        patterns:
          - "@commitlint/*"
      jest:
        patterns:
          - "jest-*"
          - "@types/jest"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    reviewers:
      - "@exadel-inc/esl-core-maintainers"
    assignees:
      - "ala-n"
      - "abarmina"
      - "NastaLeo"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      gh-pages:
        patterns:
          - "actions/configure-pages"
          - "actions/upload-pages-artifact"
          - "actions/deploy-pages"
