# Library's global linting rules
env:
  browser: true
  es6: true
  es2017: true

# Base rule sets
extends:
  # Recommended sets list
  - 'eslint:recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'

  # Library base set
  - './linting/codestyle.eslintrc.yml'
  - './linting/coderules.eslintrc.yml'
  - './linting/import.eslintrc.yml'
  - './linting/sonarjs.eslintrc.yml'
  - './linting/tests.eslintrc.yml'

# TS configuration
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.eslint.json'
  sourceType: module

# Lint additional plugins
plugins:
  - 'import'
  - 'sonarjs'
  - 'editorconfig'
  - '@typescript-eslint'
  - 'eslint-plugin-tsdoc'
  - '@html-eslint'


overrides:
  - files:
      - '*.njk'
      - '*.html'
    parser: '@html-eslint/parser'
    extends:
      - 'plugin:@html-eslint/recommended'
    excludedFiles: '*.ts'
    rules:
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': off
      '@typescript-eslint/await-thenable': off
      '@typescript-eslint/no-unnecessary-qualifier': off
      '@typescript-eslint/no-unnecessary-type-assertion': off
      '@typescript-eslint/require-array-sort-compare': off
      '@typescript-eslint/no-base-to-string': off
      '@typescript-eslint/no-unnecessary-type-arguments': off
      '@typescript-eslint/non-nullable-type-assertion-style': off
      '@typescript-eslint/no-implied-eval': off
      '@typescript-eslint/no-throw-literal': off
      '@typescript-eslint/return-await': off
      'spaced-comment': off
      '@html-eslint/require-doctype': off
      '@html-eslint/require-lang': off
      '@html-eslint/require-title': off
      'max-len': off
      'max-lines': off
      '@html-eslint/require-closing-tags': off
      '@html-eslint/no-duplicate-attrs': off
      '@html-eslint/indent': ["error", 3]


# Overall rules
rules:
  # Enable TS Doc syntax check
  'tsdoc/syntax': warn

  # Enforce charset check
  'editorconfig/charset': warn
  # Enforce EOL for all files
  'editorconfig/eol-last': warn
  # Require no trailing spaces
  'editorconfig/no-trailing-spaces': warn
