# Library's global linting rules
env:
  browser: true
  es6: true
  es2017: true

# Base rule sets
extends:
  # Recommended sets list
  - 'eslint:recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@exadel/esl/default'

  # Library base set
  - './linting/codestyle.eslintrc.yml'
  - './linting/coderules.eslintrc.yml'
  - './linting/import.eslintrc.yml'
  - './linting/sonarjs.eslintrc.yml'
  - './linting/tests.eslintrc.yml'
  - './linting/eslint.eslintrc.yml'

# TS configuration
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
    - './e2e/tsconfig.json'
    - './site/tsconfig.json'
    - './eslint/tsconfig.json'
  sourceType: module

# Lint additional plugins
plugins:
  - 'tsdoc'
  - 'import'
  - 'sonarjs'
  - 'editorconfig'
  - '@typescript-eslint'
  - '@exadel/esl'

# Overall rules
rules:
  # Enable TS Doc syntax check
  'tsdoc/syntax': warn

  # Enforce charset check
  'editorconfig/charset': warn
  # Enforce EOL for all files
  'editorconfig/eol-last': warn
  # Require no trailing spaces
  'editorconfig/no-trailing-spaces': warn
