git:
  tagName: "v${version}"
  commitMessage: "chore(release): v${version} \n\n${changelog}"
  requireCleanWorkingDir: false

hooks:
  "before:init":
    - echo Release Process started
    - npm run build
    - npm run test
    - echo Pre-release check passed
  "after:release":
    - echo Successfully released ${name} v${version} to ${repo.repository}.

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    strictSemVer: true
    preset: angular

# Out
github:
  release: false
  comments: true
  assets:
    - target/*.tgz
    - CHANGELOG.md
# TODO: Automate github issue labels

npm:
  publish: false
