# Stack trace is required
debug: true

# Tag format config
tagFormat: "v${version}"

# Repository
repositoryUrl: "https://github.com/exadel-inc/esl"

# Branch release rules
branches:
  - main
  - name: main-beta
    channel: beta
    prerelease: beta
  - name: main-next
    channel: next
    prerelease: next
  # Maintenance branches:
  - name: release-4.x
    channel: 4.x

# Release configuration
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: style
          release: patch
        - type: refactor
          release: patch
        - type: fix
          message: "*MINOR VERSION*"
          release: minor
        - type: style
          message: "*MINOR VERSION*"
          release: minor
        - type: refactor
          message: "*MINOR VERSION*"
          release: minor
        - type: chore
          scope: deps
          release: patch
        - type: chore
          scope: patch
          release: patch
        - type: feat
          scope: lint
          release: patch

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING-CHANGE

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  - - "@semantic-release/npm"
    - tarballDir: ./

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - site/package.json
        - eslint-plugin/package.json
      message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - path: ./exadel-esl-*.tgz
          label: Released Core NPM Tarball
        - path: ./exadel-eslint-plugin-esl-*.tgz
          label: Released ESLint NPM Tarball
        - path: CHANGELOG.md
          label: Changelog
