git:
  tagName: "v${version}"
  commitMessage: "chore(release): v${version} \n\n${changelog}"
  requireCleanWorkingDir: false
  push: false

hooks:
  "before:init": echo Before
  "after:release": echo Successfully released ${name} v${version} to ${repo.repository}.

plugins:
  "@release-it/bumper":
    out:
      - package.json
      - package-lock.json

  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    strictSemVer: true
    preset: angular


# Out
github:
  release: false
npm: false
