files:
  - filePath: './eslint/package.json'
    patterns:
      - '"name"\s*:\s*"\@exadel\/eslint-plugin-esl"[^{}]*"version"\s*:\s*"(\d+\.\d+\.\d+)"'
      - '"@exadel\/esl\": \"\^(\d+\.\d+\.\d+)\"'
