brand: Exadel Smart Library
description: ESL — A Web Components Library

url: "https://esl-ui.com"
copyright: "Exadel, Inc."

socialImagePath: "/assets/social-card.png"

github:
  url: "https://github.com/exadel-inc/esl"
  srcUrl: "https://github.com/exadel-inc/esl/tree/main/"

sitemapCollections:
  - index
  - introduction
  - core
  - components
  - examples
  - playground
  - news

rewriteBasePaths:
  "@exadel/esl/modules": "/packages/esl/src"
  "@exadel/esl": "/packages/esl"
  "@exadel/ui-playground/dist": "/packages/ui-playground/src"
  "@exadel/ui-playground": "/packages/ui-playground"

rewriteRules:
  "CONTRIBUTING.md": "/introduction/contributing"
  "docs/INSTALLATION_GUIDE.md": "/introduction"
  "docs/BROWSER_SUPPORT.md": "/introduction/browser-support"

  "esl-base-element/README.md": "/core/esl-base-element"
  "esl-mixin-element/README.md": "/core/esl-mixin-element"
  "esl-media-query/README.md": "/core/esl-media-query"
  "esl-traversing-query/README.md": "/core/esl-traversing-query"

  "esl-event-listener/README.md": "/core/esl-event-listener"
  "esl-event-listener/docs/1-overview.md": "/core/esl-event-listener/overview"
  "esl-event-listener/docs/2-public-api.md": "/core/esl-event-listener/public-api"
  "esl-event-listener/docs/3-extended-targets.md": "/core/esl-event-listener/extended-targets"
  "esl-event-listener/docs/4-core-support.md": "/core/esl-event-listener/core-support"

  # Decorators documentation rewrite rules
  "esl-utils/decorators/README.md": "/core/decorators"
  "esl-utils/decorators/docs/attr.md": "/core/decorators/attr"
  "esl-utils/decorators/docs/bool-attr.md": "/core/decorators/bool-attr"
  "esl-utils/decorators/docs/json-attr.md": "/core/decorators/json-attr"
  "esl-utils/decorators/docs/prop.md": "/core/decorators/prop"
  "esl-utils/decorators/docs/bind.md": "/core/decorators/bind"
  "esl-utils/decorators/docs/decorate.md": "/core/decorators/decorate"
  "esl-utils/decorators/docs/memoize.md": "/core/decorators/memoize"
  "esl-utils/decorators/docs/ready.md": "/core/decorators/ready"
  "esl-utils/decorators/docs/safe.md": "/core/decorators/safe"
  "esl-utils/decorators/docs/listen.md": "/core/decorators/listen"

  "esl-trigger/README.md": "/components/esl-trigger"
  "esl-toggleable/README.md": "/components/esl-toggleable"
  "esl-tab/README.md": "/components/esl-tab"
  "esl-panel/README.md": "/components/esl-panel"
  "esl-panel-group/README.md": "/components/esl-panel-group"
  "esl-image/README.md": "/components/esl-image"
  "esl-image-utils/README.md": "/components/esl-image-utils"
  "esl-drag-to-scroll/README.md": "/components/esl-drag-to-scroll"

  "esl-carousel/README.md": "/components/esl-carousel"
  "esl-carousel/plugin/dots/README.md": "/components/esl-carousel/dots"
  "esl-carousel/plugin/nav/README.md": "/components/esl-carousel/nav"
  "esl-carousel/plugin/autoplay/README.md": "/components/esl-carousel/autoplay"
  "esl-carousel/plugin/touch/README.md": "/components/esl-carousel/touch"
  "esl-carousel/plugin/keyboard/README.md": "/components/esl-carousel/keyboard"
  "esl-carousel/plugin/relation/README.md": "/components/esl-carousel/relation"
  "esl-carousel/plugin/wheel/README.md": "/components/esl-carousel/wheel"

  # Playground rewrite rules
  "ui-playground/src/core/README.md": "/playground/basic/core"
  "ui-playground/src/core/base/README.md": "/playground/basic/api"
  "ui-playground/src/plugins/snippets/README.md": "/playground/basic/snippets"
