brand: Exadel Smart Library
description: ESL — A Web Components Library

url: "https://esl-ui.com"

github:
  url: "https://github.com/exadel-inc/esl"
  srcUrl: "https://github.com/exadel-inc/esl/tree/main/"

sitemapCollections:
  - indexed
  - introduction
  - core
  - components
  - examples
  - news

rewriteRules:
  "CONTRIBUTING.md": "/introduction/contributing"
  "docs/INSTALLATION_GUIDE.md": "/introduction"
  "docs/BROWSER_SUPPORT.md": "/introduction/browser-support"
  "src/modules/esl-base-element/README.md": "/core/esl-base-element"
  "src/modules/esl-media-query/README.md": "/core/esl-media-query"
  "src/modules/esl-traversing-query/README.md": "/core/esl-traversing-query"
  "src/modules/esl-trigger/README.md": "/components/esl-trigger"
  "src/modules/esl-toggleable/README.md": "/components/esl-toggleable"
