brand: Exadel Smart Library
description: ESL — A Web Components Library

url: "https://esl-ui.com"

socialImagePath: "/assets/social-card.png"

github:
  url: "https://github.com/exadel-inc/esl"
  srcUrl: "https://github.com/exadel-inc/esl/tree/main/"

sitemapCollections:
  - index
  - introduction
  - core
  - components
  - examples
  - news

rewriteRules:
  "CONTRIBUTING.md": "/introduction/contributing"
  "docs/INSTALLATION_GUIDE.md": "/introduction"
  "docs/BROWSER_SUPPORT.md": "/introduction/browser-support"

  "src/modules/esl-base-element/README.md": "/core/esl-base-element"
  "src/modules/esl-mixin-element/README.md": "/core/esl-mixin-element"
  "src/modules/esl-media-query/README.md": "/core/esl-media-query"
  "src/modules/esl-traversing-query/README.md": "/core/esl-traversing-query"

  "src/modules/esl-event-listener/README.md": "/core/esl-event-listener"
  "src/modules/esl-event-listener/docs/1-overview.md": "/core/esl-event-listener/overview"
  "src/modules/esl-event-listener/docs/2-public-api.md": "/core/esl-event-listener/public-api"
  "src/modules/esl-event-listener/docs/3-extended-targets.md": "/core/esl-event-listener/extended-targets"
  "src/modules/esl-event-listener/docs/4-core-support.md": "/core/esl-event-listener/core-support"

  "src/modules/esl-trigger/README.md": "/components/esl-trigger"
  "src/modules/esl-toggleable/README.md": "/components/esl-toggleable"
  "src/modules/esl-tab/README.md": "/components/esl-tab"
  "src/modules/esl-panel/README.md": "/components/esl-panel"
  "src/modules/esl-panel-group/README.md": "/components/esl-panel-group"
  "src/modules/esl-image/README.md": "/components/esl-image"
  "src/modules/esl-image-utils/README.md": "/components/esl-image-utils"
  "src/modules/esl-drag-to-scroll/README.md": "/components/esl-drag-to-scroll"

  "src/modules/esl-carousel/README.md": "/components/esl-carousel"
  "src/modules/esl-carousel/plugin/dots/README.md": "/components/esl-carousel/esl-carousel-dots"
  "src/modules/esl-carousel/plugin/nav/README.md": "/components/esl-carousel/esl-carousel-nav"
