# Here is a run configuration for EcmaScript projects (with Babel).

env:
  browser: true
  es6: true
  es2017: true

# Base rule sets
extends:
  - 'plugin:@exadel/esl/default'

# TS configuration
parser: '@babel/eslint-parser'

# Lint additional plugins
plugins:
  - '@exadel/esl'
