#-----------------------------
# CI Github Action: Lint
#-----------------------------

name: lint

on:
  push:
    branches: [ main, main-beta ]
  pull_request:
    branches: [ main, main-beta ]
  workflow_dispatch:

env:
  node-version: 20.x

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ env.node-version }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Run Linting JS
        run: npm run lint:js
      - name: Run Linting CSS
        run: npm run lint:css
