#-----------------------------
# CI Github Action: Release
#-----------------------------

name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        default: true
        required: false
        description: 'Run in dry-run mode (no actual release)'

env:
  node-version: 20.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ env.node-version }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Semantic Release in Dry Run mode
        if: ${{ inputs.dryRun }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx semantic-release --dry-run

      - name: Run Semantic Release
        if: ${{ !inputs.dryRun }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx semantic-release
