plugins:
  # Custom plugin to disallow absolute import paths
  - ../../build/import.stylelint.js
# Use LESS preprocessor
customSyntax: postcss-less

extends:
  - '@exadel/stylelint-config-esl'

rules:
  # Disallow absolute paths for imports in bounds of library files
  esl-less/import-root: never
  # Disallow duplicate properties within declaration blocks
  declaration-block-no-duplicate-properties: true
