name: Release PR

on:
  #  push:
  #    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  node-version: 20.x

jobs:
  release-pr:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Deep Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install NPM Dependencies
        run: npm ci

#      - name: Set Git user globally to github-actions
#        uses: gotmax23/set-bot-git-user-action@main
#        with:
#          global: true
#          bot: github-actions
#          name: "Github Actions: Release PR Bot"

      - name: Version Bump (Lerna)
        run: npx lerna version --conventional-commits --yes

      - name: Store the new version
        id: info
        uses: actions/github-script@v7
        with:
          script: |
            const version = require('./lerna.json').version;
            console.log('Current version:', version);
            core.setOutput('version', version);

      # Open a PR from release/main to main
      - if: steps.info.outputs.version
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/main
          title: "Auto PR: release/main → main (v${{ steps.info.outputs.version }})"
          commit-message: 'chore: release v${{ steps.info.outputs.version }}'
          body: "This is an automated Release PR for version v${{ steps.info.outputs.version }}."
          draft: true
          labels: "automated-pr"
          assignees: "ala-n"
