name: Release PR

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  node-version: 20.x

jobs:
  release-pr:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Deep Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install NPM Dependencies
        run: npm ci

#      - name: Store current version
#        id: current_version
#        run: echo "version=$(jq -r '.version' lerna.json)" >> $GITHUB_ENV

      - name: Version Bump (Lerna)
        run: npx lerna version --conventional-commits --yes

      - name: Store the new version
        id: info
        run: echo "version=$(jq -r '.version' lerna.json)" >> $GITHUB_ENV

      - name: Set Git user globally to github-actions
        uses: gotmax23/set-bot-git-user-action@main
        with:
          global: true
          bot: github-actions
          name: "Github Actions: Release PR Bot"


      - name: Push staged changes to release/main branch
        run: |
            git checkout -b release/main
            git add .
            git commit -m "Release v${{ steps.info.outputs.version }}"
            git push origin release/main --force

      # Open a PR from release/main to main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ github.event.inputs.base || 'main' }}
          branch: release/main
          title: "Auto PR: release/main → main (v${{ steps.info.outputs.version }})"
          body: "This is an automated Release PR"
          labels: "automated-pr"
          assignees: "ala-n"
