name: Release PR

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  node-version: 20.x

jobs:
  release-pr:
    name: Release Please
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Open a PR from release/main to main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: release/main
          title: "Auto PR: release/main → main"
          body: "This is an automated Release PR"
          labels: "automated-pr"
          assignees: "ala-n"
