name: GH Pages

on:
#  schedule:
#    # Automatic build runs at 0:00 UTC daily
#    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  node-version: 20.x

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allows only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build-site:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ env.node-version }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build ESL & Site
        run: npm run build:website
        env:
          SITE_ENV: production
          SITE_BASE_URL: ${{ steps.pages.outputs.base_url }}
          BUILD_VERSION: ${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/esl-website/dist

  # Deployment job
  deploy-site:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
